### ISSUE TITLE
ObjectID rejected by native Mongo driver

### ISSUE THREAD

**Issue by imike57** [primus/ejson#62]
Hello,

I would like to use ejson with native mongodb driver and nodeJS.

But if I create a model with _id : MongoDb.ObjectID  Type. And convert to ejson and parse again, ObjectID will be rejected by mongo during save :

Original MongoDb.ObjectID object
![image](https://user-images.githubusercontent.com/24215428/84682556-1abe5f00-af36-11ea-8248-16ad9f873200.png)

toJSONValue 
![image](https://user-images.githubusercontent.com/24215428/84682843-8acce500-af36-11ea-951d-67b8a7c662d3.png)

Then after parsing I will got 
![image](https://user-images.githubusercontent.com/24215428/84682708-548f6580-af36-11ea-8e10-ea112c1b9f0f.png)

So the result is not exactly the same. And after trying to save in mongo I got 

> Error: object [{"_bsontype":"ObjectID","id":{"0":94,"1":231,"2":159,"3":38,"4":182,"5":28,"6":78,"7":125,"8":187,"9":83,"10":55,"11":123}}] is not a valid ObjectId
    at serializeObjectId (/Users/mm/Documents/py1/node_modules/bson/lib/bson/parser/serializer.js:287:11)
    at serializeInto (/Users/mm/Documents/py1/node_modules/bson/lib/bson/parser/serializer.js:931:17)
    at serializeObject (/Users/mm/Documents/py1/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/Users/mm/Documents/py1/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/Users/mm/Documents/py1/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/Users/mm/Documents/py1/node_modules/bson/lib/bson/parser/serializer.js:937:17)
    at BSON.serialize (/Users/mm/Documents/py1/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/connection/msg.js:125:22)
    at Msg.makeDocumentSegment (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/connection/msg.js:117:33)
    at Msg.toBin (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/connection/msg.js:103:25)
    at serializeCommand (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/connection/pool.js:740:41)
    at Pool.write (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/connection/pool.js:897:3)
    at _command (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/wireprotocol/command.js:107:10)
    at command (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/wireprotocol/command.js:25:5)
    at writeCommand (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/wireprotocol/write_command.js:47:3)
    at Object.insert (/Users/mm/Documents/py1/node_modules/mongodb/lib/core/wireprotocol/index.js:6:5)

There is a way to specify the expected format for ObjectID ? 

thank's

**Comment by imike57** [comment]
OK I fixed my problem with using EJSON from https://github.com/mongodb/js-bson
